[PHP]
error_reporting = E_ALL
log_errors = On
error_log = /dev/stderr
display_errors = Off
memory_limit = 512M
session.save_path = "/storage/sessions"
session.cookie_httponly = 1
session.cookie_secure = 0

[Date]
date.timezone = "Europe/Vilnius"
