[PHP]
error_reporting = E_ALL
log_errors = On
error_log = /dev/stderr
display_errors = Off
memory_limit = 512M
session.save_path = "/var/www/html/storage/sessions"

[Date]
date.timezone = "Europe/Vilnius"
